dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  # - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build:prod
