name: NPM CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
